--!path of mod
factions_modpath = minetest.get_modpath("factions")

dofile (factions_modpath .. "/config.lua")
dofile (factions_modpath .. "/storagedb.lua")
dofile (factions_modpath .. "/databases.lua")
dofile (factions_modpath .. "/eventcallbacks.lua")
dofile (factions_modpath .. "/diplomacy_events.lua")
dofile (factions_modpath .. "/invite_events.lua")
dofile (factions_modpath .. "/player_events.lua")
dofile (factions_modpath .. "/power_events.lua")
dofile (factions_modpath .. "/protection_override.lua")
dofile (factions_modpath .. "/rank_events.lua")
dofile (factions_modpath .. "/hud.lua")
dofile (factions_modpath .. "/claim_events.lua")
dofile (factions_modpath .. "/factions.lua")
dofile (factions_modpath .. "/chatcommands.lua")
dofile (factions_modpath .. "/nodes.lua")

minetest.after(1, hudUpdateClaimInfo)
minetest.after(factions_config.tick_time, factionUpdate)
